//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNetConfig.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccnet.config file not found in {0}.
        /// </summary>
        internal static string ConfigFileNotFoundMessage {
            get {
                return ResourceManager.GetString("ConfigFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Version: {0}.
        /// </summary>
        internal static string ConfigVersionStatusLabelFormat {
            get {
                return ResourceManager.GetString("ConfigVersionStatusLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all of your backup files?.
        /// </summary>
        internal static string ConfirmDeleteBackupsMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteBackupsTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteBackupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected backup files?.
        /// </summary>
        internal static string ConfirmDeleteSelectedBackupsMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy{1} of {0}.
        /// </summary>
        internal static string CopyOfProject {
            get {
                return ResourceManager.GetString("CopyOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} As....
        /// </summary>
        internal static string CopyProjectAsMenuItem {
            get {
                return ResourceManager.GetString("CopyProjectAsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0}.
        /// </summary>
        internal static string CopyProjectMenuItem {
            get {
                return ResourceManager.GetString("CopyProjectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/?[^&gt;]*&gt;.
        /// </summary>
        internal static string HtmlRegexPattern {
            get {
                return ResourceManager.GetString("HtmlRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCNet Configuration|ccnet.config|Configuration Files|*.config|XML Files|*.xml|All Files|*.*.
        /// </summary>
        internal static string OpenSaveFilter {
            get {
                return ResourceManager.GetString("OpenSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save configuration..
        /// </summary>
        internal static string UnableToSaveConfiguration {
            get {
                return ResourceManager.GetString("UnableToSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Info-ZIP License.
        /// </summary>
        internal static string UnzipLicenseText {
            get {
                return ResourceManager.GetString("UnzipLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available for CCNetConfig. Click &apos;Update Now&apos; below to update to version {0}..
        /// </summary>
        internal static string UpdatesAvailableMessage {
            get {
                return ResourceManager.GetString("UpdatesAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Not Selected..
        /// </summary>
        internal static string VersionNotSelected {
            get {
                return ResourceManager.GetString("VersionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a version before continuing..
        /// </summary>
        internal static string VersionNotSelectedMessage {
            get {
                return ResourceManager.GetString("VersionNotSelectedMessage", resourceCulture);
            }
        }
    }
}
