//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace CCNetConfig.BugTracking.org.ccnetconfig.services {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BugTrackerSoap", Namespace="http://services.ccnetconfig.org/")]
    public partial class BugTracker : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateWorkItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkItemTypeNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkItemTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BugTracker() {
            this.Url = global::CCNetConfig.BugTracking.Properties.Settings.Default.CCNetConfig_BugTracking_org_ccnetconfig_services_BugTracker;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateWorkItemCompletedEventHandler CreateWorkItemCompleted;
        
        /// <remarks/>
        public event GetWorkItemTypeNamesCompletedEventHandler GetWorkItemTypeNamesCompleted;
        
        /// <remarks/>
        public event GetWorkItemTypesCompletedEventHandler GetWorkItemTypesCompleted;
        
        /// <remarks/>
        public event GetProjectsCompletedEventHandler GetProjectsCompleted;
        
        /// <remarks/>
        public event GetProjectIdCompletedEventHandler GetProjectIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ccnetconfig.org/CreateWorkItem", RequestNamespace="http://services.ccnetconfig.org/", ResponseNamespace="http://services.ccnetconfig.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateWorkItem(string appid, TfsWorkItem workItem) {
            this.Invoke("CreateWorkItem", new object[] {
                        appid,
                        workItem});
        }
        
        /// <remarks/>
        public void CreateWorkItemAsync(string appid, TfsWorkItem workItem) {
            this.CreateWorkItemAsync(appid, workItem, null);
        }
        
        /// <remarks/>
        public void CreateWorkItemAsync(string appid, TfsWorkItem workItem, object userState) {
            if ((this.CreateWorkItemOperationCompleted == null)) {
                this.CreateWorkItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWorkItemOperationCompleted);
            }
            this.InvokeAsync("CreateWorkItem", new object[] {
                        appid,
                        workItem}, this.CreateWorkItemOperationCompleted, userState);
        }
        
        private void OnCreateWorkItemOperationCompleted(object arg) {
            if ((this.CreateWorkItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWorkItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ccnetconfig.org/GetWorkItemTypeNames", RequestNamespace="http://services.ccnetconfig.org/", ResponseNamespace="http://services.ccnetconfig.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetWorkItemTypeNames(string appid, string server, int projectId) {
            object[] results = this.Invoke("GetWorkItemTypeNames", new object[] {
                        appid,
                        server,
                        projectId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkItemTypeNamesAsync(string appid, string server, int projectId) {
            this.GetWorkItemTypeNamesAsync(appid, server, projectId, null);
        }
        
        /// <remarks/>
        public void GetWorkItemTypeNamesAsync(string appid, string server, int projectId, object userState) {
            if ((this.GetWorkItemTypeNamesOperationCompleted == null)) {
                this.GetWorkItemTypeNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkItemTypeNamesOperationCompleted);
            }
            this.InvokeAsync("GetWorkItemTypeNames", new object[] {
                        appid,
                        server,
                        projectId}, this.GetWorkItemTypeNamesOperationCompleted, userState);
        }
        
        private void OnGetWorkItemTypeNamesOperationCompleted(object arg) {
            if ((this.GetWorkItemTypeNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkItemTypeNamesCompleted(this, new GetWorkItemTypeNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ccnetconfig.org/GetWorkItemTypes", RequestNamespace="http://services.ccnetconfig.org/", ResponseNamespace="http://services.ccnetconfig.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TfsWorkItemType[] GetWorkItemTypes(string appid, string server, int projectId) {
            object[] results = this.Invoke("GetWorkItemTypes", new object[] {
                        appid,
                        server,
                        projectId});
            return ((TfsWorkItemType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkItemTypesAsync(string appid, string server, int projectId) {
            this.GetWorkItemTypesAsync(appid, server, projectId, null);
        }
        
        /// <remarks/>
        public void GetWorkItemTypesAsync(string appid, string server, int projectId, object userState) {
            if ((this.GetWorkItemTypesOperationCompleted == null)) {
                this.GetWorkItemTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkItemTypesOperationCompleted);
            }
            this.InvokeAsync("GetWorkItemTypes", new object[] {
                        appid,
                        server,
                        projectId}, this.GetWorkItemTypesOperationCompleted, userState);
        }
        
        private void OnGetWorkItemTypesOperationCompleted(object arg) {
            if ((this.GetWorkItemTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkItemTypesCompleted(this, new GetWorkItemTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ccnetconfig.org/GetProjects", RequestNamespace="http://services.ccnetconfig.org/", ResponseNamespace="http://services.ccnetconfig.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TfsProject[] GetProjects(string appid, string server) {
            object[] results = this.Invoke("GetProjects", new object[] {
                        appid,
                        server});
            return ((TfsProject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectsAsync(string appid, string server) {
            this.GetProjectsAsync(appid, server, null);
        }
        
        /// <remarks/>
        public void GetProjectsAsync(string appid, string server, object userState) {
            if ((this.GetProjectsOperationCompleted == null)) {
                this.GetProjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectsOperationCompleted);
            }
            this.InvokeAsync("GetProjects", new object[] {
                        appid,
                        server}, this.GetProjectsOperationCompleted, userState);
        }
        
        private void OnGetProjectsOperationCompleted(object arg) {
            if ((this.GetProjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectsCompleted(this, new GetProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ccnetconfig.org/GetProjectId", RequestNamespace="http://services.ccnetconfig.org/", ResponseNamespace="http://services.ccnetconfig.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetProjectId(string appid, string server, string projectName) {
            object[] results = this.Invoke("GetProjectId", new object[] {
                        appid,
                        server,
                        projectName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectIdAsync(string appid, string server, string projectName) {
            this.GetProjectIdAsync(appid, server, projectName, null);
        }
        
        /// <remarks/>
        public void GetProjectIdAsync(string appid, string server, string projectName, object userState) {
            if ((this.GetProjectIdOperationCompleted == null)) {
                this.GetProjectIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectIdOperationCompleted);
            }
            this.InvokeAsync("GetProjectId", new object[] {
                        appid,
                        server,
                        projectName}, this.GetProjectIdOperationCompleted, userState);
        }
        
        private void OnGetProjectIdOperationCompleted(object arg) {
            if ((this.GetProjectIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectIdCompleted(this, new GetProjectIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class TfsWorkItem {
        
        private string tfsServerField;
        
        private int projectIdField;
        
        private BugTrackerFile[] attachmentsField;
        
        private string workItemTypeNameField;
        
        private string descriptionField;
        
        private string titleField;
        
        private TfsField[] fieldsField;
        
        /// <remarks/>
        public string TfsServer {
            get {
                return this.tfsServerField;
            }
            set {
                this.tfsServerField = value;
            }
        }
        
        /// <remarks/>
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public BugTrackerFile[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        public string WorkItemTypeName {
            get {
                return this.workItemTypeNameField;
            }
            set {
                this.workItemTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public TfsField[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class BugTrackerFile {
        
        private byte[] fileDataField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileData {
            get {
                return this.fileDataField;
            }
            set {
                this.fileDataField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class TfsProject {
        
        private string nameField;
        
        private int idField;
        
        private string uriField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class TfsWorkItemFieldDefinition {
        
        private string systemTypeField;
        
        private FieldType fieldTypeField;
        
        private string referenceNameField;
        
        private string nameField;
        
        private bool isQueryableField;
        
        private bool isEditableField;
        
        private bool isComputedField;
        
        private int idField;
        
        private string helpTextField;
        
        private bool canSortByField;
        
        private string[] allowedValuesField;
        
        /// <remarks/>
        public string SystemType {
            get {
                return this.systemTypeField;
            }
            set {
                this.systemTypeField = value;
            }
        }
        
        /// <remarks/>
        public FieldType FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsQueryable {
            get {
                return this.isQueryableField;
            }
            set {
                this.isQueryableField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEditable {
            get {
                return this.isEditableField;
            }
            set {
                this.isEditableField = value;
            }
        }
        
        /// <remarks/>
        public bool IsComputed {
            get {
                return this.isComputedField;
            }
            set {
                this.isComputedField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string HelpText {
            get {
                return this.helpTextField;
            }
            set {
                this.helpTextField = value;
            }
        }
        
        /// <remarks/>
        public bool CanSortBy {
            get {
                return this.canSortByField;
            }
            set {
                this.canSortByField = value;
            }
        }
        
        /// <remarks/>
        public string[] AllowedValues {
            get {
                return this.allowedValuesField;
            }
            set {
                this.allowedValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public enum FieldType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        PlainText,
        
        /// <remarks/>
        Html,
        
        /// <remarks/>
        TreePath,
        
        /// <remarks/>
        History,
        
        /// <remarks/>
        Double,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class TfsWorkItemType {
        
        private TfsWorkItemFieldDefinition[] fieldDefinitionsField;
        
        private string displayFormField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        public TfsWorkItemFieldDefinition[] FieldDefinitions {
            get {
                return this.fieldDefinitionsField;
            }
            set {
                this.fieldDefinitionsField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayForm {
            get {
                return this.displayFormField;
            }
            set {
                this.displayFormField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ccnetconfig.org/")]
    public partial class TfsField {
        
        private string valueField;
        
        private string referenceNameField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateWorkItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetWorkItemTypeNamesCompletedEventHandler(object sender, GetWorkItemTypeNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkItemTypeNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkItemTypeNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetWorkItemTypesCompletedEventHandler(object sender, GetWorkItemTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkItemTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkItemTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TfsWorkItemType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TfsWorkItemType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetProjectsCompletedEventHandler(object sender, GetProjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TfsProject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TfsProject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetProjectIdCompletedEventHandler(object sender, GetProjectIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591